project:
  type: website
  output-dir: docs
  resources:
    - files/**
    - websitematerial/**
    - media/**
    - adventures/**

website:
  title: "Ethan Mathews"
  favicon: media/portfolio.png
  site-url: https://ethan-mathews24.github.io
  repo-url: https://github.com/ethan-mathews24/ethan-mathews24.github.io
  navbar:
    title: "Ethan Mathews"
    logo: media/portfolio.png
    right:
      - href: index.qmd
        text: home
      - text: about me
        menu:
          - text: pets
            href: pets.qmd
          - text: hobbies
            href: hobbies.qmd
          - text: true passion
            href: true-passion.qmd
      - href: projects.qmd
        text: projects
      - href: past-adventures.qmd
        text: past adventures
      - href: files/CV2026.pdf
        text: CV
  page-footer:
    background: light # or `dark`
    left: Copyright 2026, Ethan Mathews

filters:
  - lightbox

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: "Poppins"
    monofont: "Fira Code"
    headingfont: "Raleway"
    css: styles.css
    toc: true
    layout: full


editor: visual
